### ISSUE TITLE
KeyError: 468

### ISSUE THREAD

**Issue by Shubhamai** [corynguyen19/midi-lstm-gan#4]
Just at the last epochs in mlp_gan.py, it gives an error,

```
Traceback (most recent call last):
  File "mlp_gan.py", line 279, in <module>
    gan.train(epochs=200, batch_size=32, sample_interval=1)
  File "mlp_gan.py", line 249, in train
    self.generate(notes)
  File "mlp_gan.py", line 263, in generate
    pred_notes = [int_to_note[int(x)] for x in pred_notes]
  File "mlp_gan.py", line 263, in <listcomp>
    pred_notes = [int_to_note[int(x)] for x in pred_notes]
KeyError: 468
```

**Comment by shreyasv11** [comment]
Hello man, were you able to solve it? If yes, then how.

**Comment by Shubhamai** [comment]
Nope, I wasn't able to solve it.
